language: r
warnings_are_errors: true
sudo: required
notifications:
  email:
    on_success: change
    on_failure: change
env:
  global:
  - CRAN: http://cran.rstudio.com
  - NOT_CRAN: true
before_install:
- echo "options(repos = c(CRAN='https://cran.rstudio.com/'))" > ~/.Rprofile
r_github_packages:
- hadley/plyr
- hadley/httr
r_binary_packages:
- XML
- RCurl
- testthat
r_packages:
- rmarkdown
after_success: git log -n 1 --format=%B | grep -iq "covr"; if [ $? -eq 0 ]; then echo
  "Checking test coverage with covr"; Rscript -e 'library(covr);coveralls()'; fi
  